# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - ldflags:
      - -s -w -X "main.version={{ .Version }}"
  - main: main.go
    binary: tfselect
    id: tfselect
    goos:
      - linux
      - darwin
    goarch:
      - amd64


archives:
  -
    # ID of this archive.
    # Defaults to `default`.
    id: tfselect

    # Builds reference which build instances should be archived in this archive.
    builds:
      - tfselect
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE

brews:
  -
    name: tfselect
    ids:
      - tfselect

    tap:
      owner: basti0nz
      name: homebrew-tap

    commit_author:
      name: versus
      email: versus.dev@gmail.com
    folder: Formula
    caveats: "Type 'tfselect' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on MacOs and Linux"
    homepage: "https://basti0nz.github.io/tfselect"
    description: "The tfselect command lets you select terraform versions."
    skip_upload: false

    conflicts:
      - terraform

    test: |
      system "#{bin}/tfselect --version"

    install: |
      bin.install "tfselect"
