# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - 
    id: tfselect
    env:
      - CGO_ENABLED=0
    binary: tfselect
    ldflags:
      - -s -w -X "main.version={{ .Version }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

universal_binaries:
  - replace: true

nfpms:
  -
    description: |
      The `tfselect` command line tool lets you select version of terraform(https://www.terraform.io/).

      If you do not have a particular version of terraform installed, `tfselect` will download the version you desire.
      The installation is minimal and easy.
      
      Once installed, simply select the version you require from the dropdown and start using terraform.
    license: MIT
    formats:
    - deb
    - rpm
    dependencies:
    - git

snapcrafts:
  -
    id: tfselect
    publish: false
    summary: A command line tool to switch between different versions of terraform
    description: |
      The `tfselect` command line tool lets you switch between different versions of terraform(https://www.terraform.io/).
      If you do not have a particular version of terraform installed, `tfselect` will download the version you desire.
      The installation is minimal and easy.
      Once installed, simply select the version you require from the dropdown and start using terraform.
    base: core18

    grade: stable
    confinement: strict

    license: MIT

archives:
  -
    # ID of this archive.
    # Defaults to `default`.
    id: tfselect

    # Builds reference which build instances should be archived in this archive.
    builds:
      - tfselect
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
  
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: tfselect
    ids:
      - tfselect
    tap:
      owner: basti0nz
      name: homebrew-tap
    commit_author:
      name: versus
      email: versus.dev@gmail.com
    folder: Formula
    caveats: "Type 'tfselect' on your command line and choose the terraform version that you want from the dropdown. This command currently only works on MacOs and Linux"
    homepage: "https://basti0nz.github.io/tfselect"
    description: "The tfselect command lets you select terraform versions."
    skip_upload: false

    conflicts:
      - terraform

    test: |
      system "#{bin}/tfselect --version"

    install: |
      bin.install "tfselect"