name: tfselect
version: git
summary: A command line tool to select version of terraform
description: |
  The `tfselect` command line tool lets you select version of terraform(https://www.terraform.io/).
  If you do not have a particular version of terraform installed, `tfselect` will download the version you desire.
  The installation is minimal and easy.
  Once installed, simply select the version you require from the dropdown and start using terraform.
architectures:
  - build-on: arm64
  - build-on: amd64
assumes: [snapd2.45]
base: core18

grade: stable
confinement: strict


apps:
  tfswitch:
    command: bin/tfselect
    plugs:
      - home
      - network
      - network-bind
      
parts:
  tfswitch:
    source: .
    plugin: go
    go-importpath: github.com/bastionz/tfselect
    build-packages:
      - gcc-multilib
#    go-buildtags:
#      - tfswitch
    override-build: 
      go build  -o ../install/bin/tfselect


